name: cuber
description: Dart implementation of Herbert Kociemba's two-phase algorithm for solving Rubik's Cube.
homepage: https://github.com/tiagohm/cuber
version: 0.3.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  test: ^1.17.9
  pedantic: ^1.11.1
