name: cuber
description: Dart implementation of Herbert Kociemba's two-phase algorithm for solving Rubik's Cube.
homepage: https://github.com/tiagohm/cuber
version: 0.3.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  equatable: ^2.0.3

dev_dependencies:
  test: ^1.21.4
  very_good_analysis: ^3.0.1
