name: cuber
description: Dart implementation of Herbert Kociemba's two-phase algorithm for solving Rubik's Cube.
homepage: https://github.com/tiagohm/cuber
version: 0.4.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  test: ^1.24.2
  lints: ^2.1.0
